version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  build_docker:
    machine:
      image: ubuntu-2004:202101-01 
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: "Build Docker Image ARM V8"
          command: |
            docker build -t pilina/cardano-node:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push -a pilina/cardano-node
workflows:
  build:
    jobs:
      - build_docker
